enum ActionTypes {
  LOAD_CITIES = 'App/LOAD_CITIES',
  LOAD_CITIES_SUCCESS = 'App/LOAD_CITIES_SUCCESS',
  LOAD_CITIES_ERROR = 'App/LOAD_CITIES_ERROR',

  SET_TEMPERATURE = 'App/SET_TEMPERATURE',
}

export default ActionTypes;
